version: '3'

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn -w 4 -b 0.0.0.0:8000 book_management.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

  grpc:
    build: ./grpc_service
    container_name: grpc_service
    ports:
      - "50051:50051"
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: book_management_db
      POSTGRES_USER: books_user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
